name: Test

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Dev Drive
        if: runner.os == 'Windows'
        uses: samypr100/setup-dev-drive@cf663fdf88945e3faaa980ec525b5bc2350fbf9d # v3
        with:
          env-mapping: |
            PNPM_HOME,{{ DEV_DRIVE }}/.pnpm
            PNPM_STORE_DIR,{{ DEV_DRIVE }}/.pnpm-store

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: .nvmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          run_install: true

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Test Node.js v18
        run: pnpm --use-node-version=18.20.4 test

      - name: Lint
        if: runner.os == 'Linux'
        run: pnpm lint
